### ISSUE TITLE
Checklist of client requirements

### ISSUE THREAD

**Issue by azaroth42** [ProjectMirador/mirador-design#23]
Here is a checklist from the specifications for client requirements. I think most if not all are covered, but you can fill it out.

- [X] Clients must render label on a Collection.
- [X] Clients must render label on a Manifest.
- [X] Clients must render label on a Canvas
- [ ] ... and should generate a label for Canvases that do not have them.
- [X] Clients must render label on a Range.
- [ ] Clients should render label on an Annotation Collection.
- [ ] Clients must render metadata on a Collection.
- [X] Clients must render metadata on a Manifest.
- [X] Clients should render metadata on a Canvas.
- [ ] Clients should render summary on a Collection.
- [ ] Clients should render summary on a Manifest.
- [ ] Clients should render summary on a Canvas.
- [ ] Clients must render requiredStatement on every resource type.
- [ ] Clients must render provider on a Collection.
- [ ] Clients must render provider on a Manifest.
- [ ] Clients should render provider on other resource types.
- [X] Clients should render thumbnail on a Collection.
- [X] Clients should render thumbnail on a Manifest.
- [ ] Clients should render thumbnail on a Canvas.
- [ ] Clients should render thumbnail on a content resource.
- [ ] Clients should process viewingDirection on a Collection.
- [ ] Clients should process viewingDirection on a Manifest.
- [ ] Clients should render homepage on a Collection, Manifest or Canvas
- [ ] Clients should render rendering on a Collection, Manifest or Canvas
- [X] Clients must process items on a Collection.
- [X] Clients must process items on a Manifest.
- [X] Clients must process items on a Canvas.
- [X] Clients must process items on an Annotation Page.
- [X] 
- [X] 
- [X]
